project:
  type: book
  output-dir: docs

book:
  title: "Mapa de uso agropecuario y bosques"
  chapters:
    - index.qmd
    - part: contenido/2020/parte-2020.qmd
      chapters:
        - contenido/2020/01-datos.qmd

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 2