project:
  type: book
  output-dir: docs

book:
  title: "Mapa de uso agropecuario y bosques"
  chapters:
    - index.qmd
    - part: contenido/2020/parte-2020.qmd
      chapters:
        - contenido/2020/00-index.qmd
        - contenido/2020/01-datos.qmd
        - contenido/2020/02-procesamiento.qmd

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 2