---
format:
  html:
    toc: false
---

# Datos {.unnumbered}

```{r}
#| label: carga-paquetes
#| echo: false
#| message: false
#| warning: false

library(DT)
```

```{r}
#| label: definicion-fuentes-datos
#| echo: false
#| message: false
#| warning: false

datos <- data.frame(
  Orden = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
  Capa = c(
    "Red vial", "Áreas Silvestres Protegidas", "Humedales", "Patrimonio Natural del Estado",
    "Caña", "Banano", "Café", "Pasto",
    "Palma", "Piña", "Cultivos", "Páramo",
    "Cobertura forestal", "Suelo desnudo", "Zonas urbanas", "Sin información"
  ),
  Tipo = c(
    "Vectorial", "Vectorial", "Vectorial", "Vectorial",
    "Vectorial", "Vectorial", "Vectorial", "Vectorial",
    "Vectorial", "Vectorial", "Vectorial", "Vectorial",
    "Vectorial", "Raster", "Raster", "Raster"
  ),
  Fuente = c(
    "???", "SINAC", "SINAC", "SINAC",
    "LAICA", "MOCUPP", "ICAFE", "MOCUPP",
    "MOCUPP", "MOCUPP", "???", "???",
    "SINAC", "Secretaría REDD", "Secretaría REDD", "Secretaría REDD"
  )
)
```

La siguiente es la lista de capas geoespaciales que se utilizaron para confeccionar el mapa.

```{r}
#| label: despliegue-datos
#| echo: false
#| message: false
#| warning: false

datos |>
  datatable(rownames = FALSE,
            options = list(
              pageLength = 16,
              language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
            ))
```
